name: Android Build & Test

on:
  pull_request:
    branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Android app
        run: ./gradlew assembleDebug
        
      - name: Cache Gradle wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: <span class="math-inline">\{\{ runner\.os \}\}\-gradle\-wrapper\-</span>{{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-wrapper-

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Android tests
        run: ./gradlew test
